[package]
name = "fire"
version = "0.1.0"
authors = ["Hugo Josefson <hugo@josefson.org>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
flame = "0.2.2"
flamer = "0.3"

[dependencies.sdl2]
version = "0.32.1"
features = ["gfx"]
