[package]
name = "fire"
version = "1.0.1"
authors = ["Hugo Josefson <hugo@josefson.org>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
rust-embed="4.3.0"
rodio = "0.8.1"

[dependencies.sdl2]
version = "0.32.1"
features = ["gfx"]
