# build like this:
#
# docker build -f Dockerfile.debian-11 .
# docker run --rm -i sha256:copy-paste-hash-from-build-output > fire-for-debian-11
# chmod +x fire-for-debian-11

FROM debian:11
RUN apt-get update && apt-get install -y \
    libsdl2-dev libsdl2-gfx-dev \
    build-essential \
    curl

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

COPY . /app
WORKDIR /app
RUN ["/root/.cargo/bin/cargo", "build", "--release"]
CMD ["cat", "./target/release/fire"]
